<?php

namespace IbrahimBougaoua\FilamentSubscription\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    public $currencies = [
        ['USD US Dollar', '$', 'USD'],
        ['EUR Euro', '€', 'EUR'],
        ['HKD Hong Kong Dollar', '$', 'HKD'],
        ['INR Indian Rupee', '₹', 'INR'],
        ['AUD Australian Dollar', '$', 'AUD'],
        ['JMD Jamaican Dollar', 'J$', 'JMD'],
        ['CAD Canadian Dollar', '$', 'CAD'],
        ['AED United Arab Emirates Dirham', 'د.إ', 'AED'],
        ['AFN Afghanistan Afghani', '؋', 'AFN'],
        ['ALL Albania Lek', 'Lek', 'ALL'],
        ['AMD Armenian Dram', '֏', 'AMD'],
        ['ANG Netherlands Antilles Guilder', 'ƒ', 'ANG'],
        ['AOA Angola kwanza', 'Kz', 'AOA'],
        ['ARS Argentina Peso', '$', 'ARS'],
        ['AWG Aruba Guilder', 'ƒ', 'AWG'],
        ['AZN Azerbaijan Manat', '₼', 'AZN'],
        ['BAM Bosnia and Herzegovina Convertible Marka', 'KM', 'BAM'],
        ['BBD Barbados Dollar', '$', 'BBD'],
        ['BDT Bangladesh Taka', '৳', 'BDT'],
        ['BGN Bulgaria Lev', 'лв', 'BGN'],
        ['BMD Bermuda Dollar', '$', 'BMD'],
        ['BND Brunei Darussalam Dollar', '$', 'BND'],
        ['BOB Bolivia Boliviano', '$b', 'BOB'],
        ['BRL Brazil Real', 'R$', 'BRL'],
        ['BSD Bahamas Dollar', '$', 'BSD'],
        ['BWP Botswana Pula', 'P', 'BWP'],
        ['BZD Belize Dollar', 'BZ$', 'BZD'],
        ['CDF Congo Congolese franc', 'FC', 'CDF'],
        ['CHF Switzerland Franc', 'CHF', 'CHF'],
        ['CNY China Yuan Renminbi', '¥', 'CNY'],
        ['COP Colombia Peso', '$', 'COP'],
        ['CRC Costa Rica Colon', '₡', 'CRC'],
        ['CVE Cape Verde Escudo', '$', 'CVE'],
        ['CZK Czech Republic Koruna', 'Kč', 'CZK'],
        ['DKK Denmark Krone', 'kr', 'DKK'],
        ['DOP Dominican Republic Peso', 'RD$', 'DOP'],
        ['DZD Algeria Dinar', 'دج', 'DZD'],
        ['EGP Egypt Pound', '£', 'EGP'],
        ['ETB Ethiopia Birr', 'ብር', 'ETB'],
        ['FJD Fiji Dollar', '$', 'FJD'],
        ['FKP Falkland Islands Pound', '£', 'FKP'],
        ['GBP United Kingdom Pound', '£', 'GBP'],
        ['GEL Georgia Lari', '₾', 'GEL'],
        ['GIP Gibraltar Pound', '£', 'GIP'],
        ['GMD Gambia Dalasi', 'D', 'GMD'],
        ['GTQ Guatemala Quetzal', 'Q', 'GTQ'],
        ['GYD Guyana Dollar', '$', 'GYD'],
        ['HNL Honduras Lempira', 'L', 'HNL'],
        ['HRK Croatia Kuna', 'kn', 'HRK'],
        ['HTG Haiti Gourde', 'G', 'HTG'],
        ['HUF Hungary Forint', 'Ft', 'HUF'],
        ['IDR Indonesia Rupiah', 'Rp', 'IDR'],
        ['ILS Israel Shekel', '₪', 'ILS'],
        ['ISK Iceland Krona', 'kr', 'ISK'],
        ['KES Kenya Shilling', '/=', 'KES'],
        ['KGS Kyrgyzstan Som', 'лв', 'KGS'],
        ['KHR Cambodia Riel', '៛', 'KHR'],
        ['KYD Cayman Dollar', '$', 'KYD'],
        ['KZT Kazakhstan Tenge', 'лв', 'KZT'],
        ['LAK Laos Kip', '₭', 'LAK'],
        ['LBP Lebanon Pound', '£', 'LBP'],
        ['LKR Sri Lanka Rupee', '₨', 'LKR'],
        ['LRD Liberia Dollar', '$', 'LRD'],
        ['LSL Lesotho Loti', 'L', 'LSL'],
        ['MAD Morocco Dirham', 'MAD', 'MAD'],
        ['MDL Moldova Leu', 'L', 'MDL'],
        ['MKD Macedonia Denar', 'ден', 'MKD'],
        ['MMK Myanmar Kyat', 'K', 'MMK'],
        ['MNT Mongolia Tughrik', '₮', 'MNT'],
        ['MOP Macau P ataca', 'MOP$', 'MOP'],
        ['MRO Mauritania Ouguiya', 'MRU', 'MRO'],
        ['MUR Mauritius Rupee', '₨', 'MUR'],
        ['MVR Maldives Rufiyaa', '.ރ', 'MVR'],
        ['MWK Malawi Kwacha', 'MK', 'MWK'],
        ['MXN Mexico Peso', '$', 'MXN'],
        ['MYR Malaysia Ringgit', 'RM', 'MYR'],
        ['MZN Mozambique Metical', 'MT', 'MZN'],
        ['NAD Namibia Dollar', '$', 'NAD'],
        ['NGN Nigeria Naira', '₦', 'NGN'],
        ['NIO Nicaragua Cordoba', 'C$', 'NIO'],
        ['NOK Norway Krone', 'kr', 'NOK'],
        ['NPR Nepal Rupee', '₨', 'NPR'],
        ['NZD New Zealand Dollar', '$', 'NZD'],
        ['PAB Panama Balboa', 'B/.', 'PAB'],
        ['PEN Peru Nuevo Sol', 'S/.', 'PEN'],
        ['PGK Papua New Guinea Kina', 'K', 'PGK'],
        ['PHP Philippines Peso', '₱', 'PHP'],
        ['PKR Pakistan Rupee', '₨', 'PKR'],
        ['PLN Poland Zloty', 'zł', 'PLN'],
        ['QAR Qatar Riyal', '﷼', 'QAR'],
        ['RON Romania New Leu', 'lei', 'RON'],
        ['RSD Serbia Dinar', 'Дин.', 'RSD'],
        ['RUB Russia Ruble', '₽', 'RUB'],
        ['SAR Saudi Arabia Riyal', '﷼', 'SAR'],
        ['SBD Solomon Islands Dollar', '$', 'SBD'],
        ['SCR Seychelles Rupee', '₨', 'SCR'],
        ['SEK Sweden Krona', 'kr', 'SEK'],
        ['SGD Singapore Dollar', '$', 'SGD'],
        ['SHP Saint Helena Pound', '£', 'SHP'],
        ['SLL Sierra Leone Leone', 'Le', 'SLL'],
        ['SOS Somalia Shilling', 'S', 'SOS'],
        ['SRD Suriname Dollar', '$', 'SRD'],
        ['STD São Tomé and Príncipe Dobra', 'Db', 'STD'],
        ['SZL Eswatini lilangeni', 'L', 'SZL'],
        ['THB Thailand Baht', '฿', 'THB'],
        ['TJS Tajikistan Somoni', 'ЅM', 'TJS'],
        ['TOP Tonga Pa’anga', 'T$', 'TOP'],
        ['TRY Turkey Lira', '₺', 'TRY'],
        ['TTD Trinidad and Tobago Dollar', 'TT$', 'TTD'],
        ['TWD Taiwan New Dollar', 'NT$', 'TWD'],
        ['TZS Tanzania Shiling', 'TSh', 'TZS'],
        ['UAH Ukraine Hryvna', '₴', 'UAH'],
        ['UYU Uruguay Peso', '$U', 'UYU'],
        ['UZS Uzbekistan Som', 'лв', 'UZS'],
        ['WST Samoa  Tālā', 'WS$', 'WST'],
        ['XCD Eastern Caribbean States Dollar', '$', 'XCD'],
        ['YER Yemen Rial', '﷼', 'YER'],
        ['ZAR South Africa Rand', 'R', 'ZAR'],
        ['ZMW Zambia Kwacha', 'ZK', 'ZMW'],
        ['BIF Burundi Franc', 'FBu', 'BIF'],
        ['CLP Chile Peso', '$', 'CLP'],
        ['DJF Djibouti Franc', 'Fdj', 'DJF'],
        ['GNF Guinea Franc', 'GFr', 'GNF'],
        ['JPY Japan Yen', '¥', 'JPY'],
        ['KMF Comoros Franc', 'CF', 'KMF'],
        ['KRW Korea Won', '₩', 'KRW'],
        ['MGA Madagascar Ariary ', 'Ar', 'MGA'],
        ['PYG Paraguay Guarani', 'Gs', 'PYG'],
        ['RWF Rwanda Franc', 'R₣', 'RWF'],
        ['UGX Uganda Shilling', 'USh', 'UGX'],
        ['VND Viet Nam Dong', '₫', 'VND'],
        ['VUV Vanuatu Vatu', 'VT', 'VUV'],
        ['XAF Central Africa Central African CFA Franc', 'FCFA', 'XAF'],
        ['XOF West Africa West African CFA Franc', 'CFA', 'XOF'],
        ['XPF France Franc', '₣', 'XPF'],
    ];

    /**
     * Run the database seeders.
     */
    public function run(): void
    {
        foreach ($this->currencies as $currency) {
            DB::table('filament_currencies')->insert([
                'name' => $currency[0],
                'icon' => $currency[1],
                'code' => $currency[2],
            ]);
        }
    }
}
